### PR TITLE
Update url from coala-analyzer to coala

### PR DESCRIPTION
**Pull request by camilaavilarinho**
Fixes https://github.com/coala/bear-docs/issues/32

### CODE REVIEW

**Review by arnab1896 — CHANGES_REQUESTED** [review]
Changes are okay! :+1: 

just modify your commit shortlog like this:-
:point_down: 
docs/*.rst: Update url from coala-analyzer to coala

so that it is in accordance with http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

follow this --> http://api.coala.io/en/latest/Developers/Git_Basics.html <--

**Comment by jayvdb** [comment]
Yup; content is good.  Commit message needs to be improved.
Use `git commit --amend` to revise the commit message, and then push the modified commit to github.

**Review by damngamerz — COMMENTED** [review]
Please add.
"Fixes/closes issue-link"
to your commit body.
As mentioned in http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by Makman2** [comment]
Just `Closes` is good, not `Fixes/closes` :D

**Comment by jayvdb** [comment]
Your commit message is currently 
```
docs/*.rst: Update url from coala-analyzer to coala
Closes https://github.com/coala/bear-docs/issues/32
```

Please add a blank line between those two lines.

**Comment by damngamerz** [comment]
ack 22ea4d4ac7ad0d3d020d2ba9a4bf37b08ae45502
seems good now !!!

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
