### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by jayvdb**
- Reverts f8d8478,
- Partially reverts 27c7e19db, 
- Fixes https://github.com/coala/coala/issues/3542 if GitHub protected branches are enabled,
- Closes https://github.com/coala/bear-docs/issues/34
- Temporary workaround for https://github.com/coala/bear-docs/issues/35

### CODE REVIEW

**Comment by jayvdb** [comment]
7f64e18 and some of a2b7cee are unnecessary if we want to push those doc changes into a new release of the bears. cc @Mixih

**Review by damngamerz — APPROVED** [review]
ack 011fa24265a60959840eaf8554df20cb43357f18
ack 9941c6824ed8e975effdb0b9031c48078df3753d
ack f3b2adc55a1707810f5c5a4260b4e24afbd61713
ack 238d7dda52098237124c41aa1e0bf6e5592d1aa8
ack 69f4c37e389541db4ed35e9eb75b09d05b62f185
ack 8541035ef2b22fa565abc98391db8e526c83306a

**Comment by jayvdb** [comment]
This is mergable, but 8541035 can be removed if [bears 0.10.2](https://github.com/coala/coala-bears/milestone/11) is released promptly.  I'll look into that today (many of those patches are mine anyway)

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
