### PR TITLE
added .rultor.yml and other files required by rultor

### PR DESCRIPTION
**Pull request by yogupta**
Copied the .misc directory and .rultor.yml file from[coala](https://github.com/coala/coala).

### CODE REVIEW

**Comment by sils** [comment]
Hi,

thanks for your contribution!

Please note that this documentation is generated from the [coala-bears](https://github.com/coala/coala-bears/) project. If you are working on rst files, you will very likely want to do changes over there instead!

**Comment by yogupta** [comment]
No i'm working on .rultor.yml

**Comment by sils** [comment]
that's ok that comment above is an autoresponse ;)

**Comment by sils** [comment]
Please check the issue again, I left you a comment when you asked me: https://github.com/coala/bear-docs/issues/26#issuecomment-271803246

**Comment by yogupta** [comment]
i have updated the .rultor.yml file now .

**Comment by sils** [comment]
your commit message doesn't comply to our standards, also you need to squash your commits, I suggest you use the `git rebase -i` to do the job, for more info use google or coala.io/git

**Comment by sils** [comment]
hey can you stop reverting things and pressing the update branch button? That's not helping :/ we need a squash. At this point I'd recommend `git reset master` and then `git commit -a` your changes again, `git push -f` them up

**Comment by yogupta** [comment]
I'm so sorry. I apologize for my mistake. :(

**Comment by sils** [comment]
no issue, really, we're all learning!

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Pull request closed without merging**
